# Netplan LAB07 - NO aplicar hasta estar conectado al puerto VLAN 99
# Destino en VM: /etc/netplan/50-lab07.yaml
# Uso en lab: sudo cp 50-lab07.yaml /etc/netplan/50-lab07.yaml && sudo netplan apply
network:
  version: 2
  ethernets:
    ens33:
      dhcp4: false
      addresses: [172.18.99.10/24]
      routes:
        - to: default
          via: 172.18.99.1
      nameservers:
        addresses: [8.8.8.8, 172.18.99.1]
