# dnsmasq - Lab 07 (opcion rapida, 1 archivo)
# Ubuntu/Debian: apt install dnsmasq
# Archivo: /etc/dnsmasq.d/lab07.conf
# Interfaz conectada a VLAN 99. Requiere ip helper en router para VLAN 30.
# NOTA: solo DHCP, DNS desactivado (port=0) porque systemd-resolved ya usa puerto 53.

interface=ens33
bind-interfaces
port=0
dhcp-authoritative
domain=lab07.local
log-dhcp

# Ambito GESTION
dhcp-range=172.18.99.100,172.18.99.180,255.255.255.0,8h
dhcp-option=option:router,172.18.99.1
dhcp-option=option:dns-server,8.8.8.8,172.18.99.1

# Ambito CCTV (via relay 172.18.30.1)
dhcp-range=172.18.30.100,172.18.30.180,255.255.255.0,8h
dhcp-option=tag:cctv,option:router,172.18.30.1

# Reservas (reemplaza MAC reales):
# dhcp-host=AA:BB:CC:DD:EE:01,172.18.30.10,nvr-hikvision,infinite
# dhcp-host=AA:BB:CC:DD:EE:02,172.18.30.20,camara1,infinite

# IP estatica del servidor (NetworkManager cli ejemplo):
# nmcli con mod "eth0" ipv4.addresses 172.18.99.10/24 ipv4.gateway 172.18.99.1 ipv4.dns "8.8.8.8 172.18.99.1" ipv4.method manual
# systemctl restart dnsmasq
# journalctl -u dnsmasq -f
# cat /var/lib/misc/dnsmasq.leases
